# Generated by Django 5.2.3 on 2025-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Turno",
            fields=[
                ("turno_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "descricao",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Descrição do Turno"
                    ),
                ),
            ],
        ),
    ]
