# Generated by Django 5.2.4 on 2025-09-05 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso_interesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.curso', verbose_name='Curso de Interesse'),
        ),
    ]
