# Generated by Django 5.2.4 on 2025-09-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_turma_curso'),
    ]

    operations = [
    ]
