# Generated by Django 5.2.4 on 2025-09-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20250920_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='periodo_interesse',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Período de Interesse'),
        ),
    ]
