# Generated by Django 5.2.4 on 2025-09-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_aluno_periodo_interesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='curso_interesse',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso_interesse',
            field=models.ManyToManyField(blank=True, to='academico.curso', verbose_name='Cursos de Interesse'),
        ),
    ]
